### ISSUE TITLE
optimization of exponential backoff delay function

### ISSUE THREAD

**Issue by casual1st** [allora-network/allora-offchain-node#79]
https://github.com/allora-network/allora-offchain-node/blame/21e4c19c0b8f98d2b7fb345d575c02ed8954d035/lib/repo_tx_utils.go#L57

There should be a maximum limit for the below parameters.
        "maxRetries": 5,
        "retryDelay": 3,
        
If someone sets maxRetries to 10 it will take 16 hours, and 24 minutes for the 10th retry which doesn't make any sense. 
We can either set a limit for the max or change the function like the below one:

func calculateExponentialBackoffDelay(baseDelay int64, retryCount int64) time.Duration {
    delay := float64(baseDelay) * math.Pow(2, float64(retryCount))
    return time.Duration(delay) * time.Second
}

**Comment by xmariachi** [comment]
The settings are there to be configured by the user and be able to tune them freely.
You're right in that certain configurations wouldn't make sense. However this is up to the user to configure as they see fit. 
Different topics will have different configurations too, so what applies to some may not apply to others.
